title: "DSC180A–Methodology–4 Assignment"

# Simple built-in theme (no extra setup)
theme: jekyll-theme-cayman

# Optional but nice to have
url: https://levsah.github.io
baseurl: /DSC180A-Methodology-4   # <- repo name (omit if using a user/organization site)
